---

- name : "playbook running tasks on ansible controller"
  block:
  - import_tasks:  "00-asserts.yml"
  # - name: "Installing base dependencies"
  #   include_tasks: 01-installer.yml
  #   loop: 
  #     - { name: ca-certificates}
  #     - { name: curl}
  #     - { name: jq}
  #     - { name: wget}
  #     - { name: sudo}
  #     - { name: unzip}
  #     - { name: apt-transport-https}
  #     - { name: ca-certificates}
  #     - { name: gnupg2}
  #     - { name: software-properties-common}
  #     - { name: ufw}
  - include_tasks: 02-install-cfssl.yml
    loop: 
      - { name: cfssl}
      - { name: cfssl-bundle}
      - { name: cfssl-certinfo}
      - { name: cfssl-newkey}
      - { name: cfssl-scan}
      - { name: cfssljson}
      - { name: mkbundle}
      - { name: multirootca}
  - import_tasks:  "03-install-kubectl.yml"
  - import_tasks:  "04-install-minikube.yml"
  - import_tasks:  "05-install-kompose.yml"
  delegate_to: localhost
  become: yes
  run_once: true