#!/bin/bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
pip_packages=(
  "python-openstackclient"
  "neutron-fwaas"
)
for i in "${extensions[@]}";do 
  python3 -m pip install "$i"
done
