#!/bin/bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
export DEBIAN_FRONTEND=noninteractive
extensions=(
"alefragnani.Bookmarks"
"alefragnani.project-manager"
"arcsine.chronicler"
"emeraldwalk.RunOnSave"
"esbenp.prettier-vscode"
"GrapeCity.gc-excelviewer"
"James-Yu.latex-workshop"
"JeffersonQin.latex-snippets-jeff"
"micnil.vscode-checkpoints"
"ms-azuretools.vscode-docker"
"ms-python.anaconda-extension-pack"
"ms-python.python"
"ms-vscode-remote.remote-containers"
"ms-vscode-remote.remote-ssh"
"ms-vscode-remote.remote-ssh-edit"
"ms-vscode-remote.remote-wsl"
"ms-vscode-remote.vscode-remote-extensionpack"
"njpwerner.autodocstring"
"quillaja.goasm"
"redhat.vscode-yaml"
"streetsidesoftware.code-spell-checker"
"tomoki1207.pdf"
"torn4dom4n.latex-support"
"VisualStudioExptTeam.vscodeintellicode"
"vscoss.vscode-ansible"
"wholroyd.HCL"
"wmaurer.change-case"
"xaver.clang-format"
"yzane.markdown-pdf"
"yzhang.markdown-all-in-one"
"zxh404.vscode-proto3"
"vscode-snippet.snippet"
"bungcip.better-toml"
"kevinkyang.auto-comment-blocks"
"lkytal.pomodoro"
"zalo.symplex"
"mechatroner.rainbow-csv"
"phplasma.csv-to-table"
"aaron-bond.better-comments"
"wayou.vscode-todo-highlight"
"DavidAnson.vscode-markdownlint"
)
for i in "${extensions[@]}";do 
  code --install-extension "$i"
done

