#!/bin/bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
export DEBIAN_FRONTEND=noninteractive

# [NOTE] => installing dependencies
sudo apt-get update -qq > /dev/null 2>&1
apt-get install -yqq apt-utils curl lsb-release wget ca-certificates gnupg2 jq > /dev/null 2>&1

# [NOTE] => installing vscode
curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -  >/dev/null 2>&1
echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" | sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
sudo apt update -qq > /dev/null 2>&1
sudo apt install -yqq code > /dev/null 2>&1

