---
- block :
  - find:
      paths: ["{{ role_path }}/templates/config"]
      file_type: file
      use_regex: yes
      patterns: ['^.*\.hcl\.j2$']
    register: "hcl_config_filelist"
    run_once: true
    delegate_to: localhost
  - set_fact:
      hcl_config_filelist: > 
        {{ 
          hcl_config_filelist.files | 
          map(attribute='path')  | 
          list | 
          regex_replace(role_path + '/templates/config.*?/','') | 
          regex_replace('\.j2','')
        }}
  - name: "uploading consul-template config files"
    template: 
      src: "config/{{ item }}.j2"
      dest: "{{ consul_template_user_home_path }}/{{ item }}"
      force: yes
      decrypt: yes
      owner: consul-template
      group: consul-template
      variable_start_string: "[["
      variable_end_string: "]]"
    loop: "{{ hcl_config_filelist }}"
    become: yes

