---

vault_tls_path : "{{ lookup('env','VAULT_TLS_PATH') | default('/opt/vault/tls', true) }}"
vault_api_port : "{{ lookup('env','VAULT_API_PORT') | default('8200', true) }}"
play_encrypted_vars_dir: "{{ inventory_dir+'/host_vars/'}}"
